version: '3.9'
services:
  dev:
    build: 
      context: .
      target: development
    ports: 
      - "5050:5050"
    volumes:
      - .:/todo-app 
    env_file: .env

  test:
    build:
      context: .
      target: test
