name: Run Tests
on:
  pull_request:
    types: [opened, reopened]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build Docker container
        run: docker build --target test --tag todo-app:test .
      - name: Run unit & integration tests
        run: docker run
               --env-file=.env.test
               todo-app:test
               tests/unit
               tests/integration
      - name: Run end to end tests
        run: docker run
               --env SECRET_KEY=${{ secrets.SECRET_KEY }}
               --env TRELLO_KEY=${{ secrets.TRELLO_KEY }}
               --env TRELLO_TOKEN=${{ secrets.TRELLO_TOKEN }}
               --env BOARD_KEY=${{ secrets.BOARD_KEY }}
               todo-app:test
               tests/e2e/test_chromium.py

  deploy:
    name: Deploy into production
    needs: run-tests
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: "${{ secrets.HEROKU_TOKEN }}"
      DOCKER_LOGIN: "${{ secrets.DOCKER_LOGIN }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
    steps:
    - uses: actions/checkout@v1
    - name: login to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
    - name: build production docker image
      run: docker build --target production --tag DOCKER_LOGIN/todo-app-production:${GITHUB_SHA::6} --tag $DOCKER_LOGIN/todo-app-production:latest .
    - name: push commit hash tagged build to Docker Hub
      run: docker push $DOCKER_LOGIN/todo-app-production:${GITHUB_SHA::6}
    - name: push latest tagged build to Docker Hub
      run: docker push $DOCKER_LOGIN/todo-app-production:latest
    - name: pull production image from Docker Hub
      run: docker pull $DOCKER_LOGIN/todo-app-production:latest
    - name: tag production image for deployment to heroku
      run: docker tag $DOCKER_LOGIN/todo-app-production:latest registry.heroku.com/todo-app-devops-academy/web
    - name: login to docker on the heroku registry
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - name: push production image to heroku registry
      run: docker push registry.heroku.com/todo-app-devops-academy/web
    - name: release the container on the heroku registry
      run: HEROKU_API_KEY=$HEROKU_API_KEY heroku container:release -a todo-app-devops-academy web 