name: Run Tests
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    types: [opened, reopened]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build Docker container
        run: docker build --target test --tag todo-app:test .
      - name: Run unit & integration tests
        run: docker run
               --env-file=.env.test
               todo-app:test
               tests/unit
               tests/integration
      - name: Run end to end tests
        run: docker run
               --env SECRET_KEY=${{ secrets.SECRET_KEY }}
               --env TRELLO_KEY=${{ secrets.TRELLO_KEY }}
               --env TRELLO_TOKEN=${{ secrets.TRELLO_TOKEN }}
               --env BOARD_KEY=${{ secrets.BOARD_KEY }}
               todo-app:test
               tests/e2e/test_chromium.py

  deploy:
    name: Deploy into production
    # needs: run-tests
    # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: "${{ secrets.HEROKU_API_KEY }}"
      DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
    - name: Build production docker image
      run: docker build --target production --tag $DOCKER_USERNAME/todo-app-production:${GITHUB_SHA::6} --tag $DOCKER_USERNAME/todo-app-production:latest .
    - name: Push commit hash tagged build to Docker Hub
      run: docker push $DOCKER_USERNAME/todo-app-production:${GITHUB_SHA::6}
    - name: Push latest tagged build to Docker Hub
      run: docker push $DOCKER_USERNAME/todo-app-production:latest
    - name: Pull production image from Docker Hub
      run: docker pull $DOCKER_USERNAME/todo-app-production:latest
    - name: Tag production image on Heroku
      run: docker tag $DOCKER_USERNAME/todo-app-production:latest registry.heroku.com/$DOCKER_USERNAME-todo/web
    - name: Login to Heroku registry
      run: echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
    - name: Push production image to Heroku registry
      run: docker push registry.heroku.com/$DOCKER_USERNAME-todo/web
    - name: Release the container on the Heroku registry
      run: HEROKU_API_KEY=$HEROKU_API_KEY heroku container:release -a $DOCKER_USERNAME-todo web 